version: '3'

services:
  apachephp71:
    image: registry.gitlab.com/rapidevelop/sppa_cms:dev
    container_name: moodle
    restart: always
    depends_on:
      - pgsql
    ports:
      - 80:80
    environment:
      MOODLE_DOCKER_MOODLE_DATA: /var/www/moodledata
      MOODLE_DOCKER_DBHOST: pgsql
      MOODLE_DOCKER_DBTYPE: pgsql
      MOODLE_DOCKER_DBNAME: "${MOODLE_DB}"
      MOODLE_DOCKER_DBUSER: "${MOODLE_DBUSER}"
      MOODLE_DOCKER_DBPASS: "${MOODLE_DBPASS}"
      MOODLE_DOCKER_WEB_HOST: "${MOODLE_HOST}"
      MOODLE_DOCKER_WEB_PORT: 80
  pgsql:
    image: postgres:9
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${MOODLE_DBUSER}"
      POSTGRES_PASSWORD: "${MOODLE_DBPASS}"
      POSTGRES_DB: "${MOODLE_DB}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "${MOODLE_PGDATA_DIR}:/var/lib/postgresql/data/pgdata"