version: '3'

services:
  moodle:
    image: registry.gitlab.com/rapidevelop/sppa_cms:latest
    container_name: moodle
    restart: always
    depends_on:
      - pgsql
    ports:
      - "${MOODLE_DOCKER_WEB_PORT}:80"
    environment:
      MOODLE_DOCKER_MOODLE_DATA: /var/www/moodledata
      MOODLE_DOCKER_DBHOST: pgsql
      MOODLE_DOCKER_DBTYPE: pgsql
      MOODLE_DOCKER_DBNAME: staging
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "${MOODLE_DOCKER_DBPASS}"
      MOODLE_DOCKER_WEB_HOST: "${MOODLE_DOCKER_WEB_HOST}"
      MOODLE_DOCKER_WEB_PORT: "${MOODLE_DOCKER_WEB_PORT}"
    volumes:
      - "${MOODLE_DOCKER_MOODLE_DATA}:/var/www/moodledata"

  pgsql:
    image: postgres:9
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: "${MOODLE_DOCKER_DBPASS}"
      POSTGRES_DB: moodle
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "${PGDATA}:/var/lib/postgresql/data/pgdata"